services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: estoque_db
      MYSQL_USER: estoque_user
      MYSQL_PASSWORD: estoque_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - estoque-network

  backend:
    build:
      context: ./estoque-api
      dockerfile: Dockerfile
    container_name: estoque-backend
    depends_on:
      - mysql-db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/estoque_db?createDatabaseIfNotExist=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: estoque_user
      SPRING_DATASOURCE_PASSWORD: estoque_pass
    networks:
      - estoque-network

  frontend:
    build:
      context: ./estoque-frontend
      dockerfile: Dockerfile
    container_name: estoque-frontend
    depends_on:
      - backend
    ports:
      - "4200:80"
    networks:
      - estoque-network

volumes:
  mysql_data:

networks:
  estoque-network:
    driver: bridge
